### ISSUE TITLE
Tests fail using gdb + clang++ compiled binaries

### ISSUE THREAD

**Issue by springmeyer** [mapbox/logbt#9]
It looks like line numbers disappear from backtraces when the default gdb on ubuntu precise is used with clang++ 4.x.

Seen with:

`CXXFLAGS="-g -O0 -DDEBUG"`

```
$ clang++ --version
mapbox/mason clang version 4.0.0 (https://github.com/mapbox/mason 441c3af190189ee0bd37e3c8e5e61a51338b08d6) (http://llvm.org/git/llvm.git 7d6a2cb700477f9d20774a0af8bcd32008bf9665) (based on LLVM 4.0.0svn)
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /home/ubuntu/mason/mason_packages/linux-x86_64/llvm/4.0.0/bin
```

```
$ gdb --version
GNU gdb (Ubuntu/Linaro 7.4-2012.04-0ubuntu2.1) 7.4-2012.04
Copyright (C) 2012 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
For bug reporting instructions, please see:
<http://bugs.launchpad.net/gdb-linaro/>.
```

```
not ok - Did not find string 'abort.cpp:2' in 'Using existing corefile location: /tmp/logbt-coredumps/core.%p
/tmp/logbt/run-test exited with code:134
Found core at /tmp/logbt-coredumps/core.27796
[New LWP 27796]
Core was generated by `/tmp/logbt/run-test'.
Program terminated with signal 6, Aborted.
#0  0x00007f98c3933035 in raise () from /lib/x86_64-linux-gnu/libc.so.6

Thread 1 (LWP 27796):
#0  0x00007f98c3933035 in raise () from /lib/x86_64-linux-gnu/libc.so.6
#1  0x00007f98c393679b in abort () from /lib/x86_64-linux-gnu/libc.so.6
#2  0x00000000004005e4 in main ()' (Found expected line number in backtrace output)
bailing tests early

dumping log of stdout
Using existing corefile location: /tmp/logbt-coredumps/core.%p
/tmp/logbt/run-test exited with code:134
Found core at /tmp/logbt-coredumps/core.27796
[New LWP 27796]
Core was generated by `/tmp/logbt/run-test'.
Program terminated with signal 6, Aborted.
#0  0x00007f98c3933035 in raise () from /lib/x86_64-linux-gnu/libc.so.6

Thread 1 (LWP 27796):
#0  0x00007f98c3933035 in raise () from /lib/x86_64-linux-gnu/libc.so.6
#1  0x00007f98c393679b in abort () from /lib/x86_64-linux-gnu/libc.so.6
#2  0x00000000004005e4 in main ()

dumping log of stderr
./bin/logbt: line 137: 27796 Aborted                 (core dumped) $*

warning: Can't read pathname for load map: Input/output error.

* Error: 1 test(s) failed
```

**Comment by springmeyer** [comment]
Solvable by doing:

```diff
diff --git a/test/unit.sh b/test/unit.sh
index 4081577..c21c531 100755
--- a/test/unit.sh
+++ b/test/unit.sh
@@ -12,7 +12,7 @@ export RESULT=0
 export WORKING_DIR="/tmp/logbt"
 export STDOUT_LOGS="./stdout.txt"
 export STDERR_LOGS="./stderr.txt"
-export CXXFLAGS="-g -O0 -DDEBUG"
+export CXXFLAGS="-gdwarf-2 -O0 -DDEBUG"
 export CXX=${CXX:-g++}
 export SIGSEGV_CODE="139"
 export SIGABRT_CODE="134"
```

Other potential workaround is to use a more recent gdb.

**Comment by springmeyer** [comment]
Confirmed that upgrading gdb works (proven in #15).
